[workspace]
members = [
    "core-engine",
    "scanner-net",
    "vuln-correlator",
    "log-analyzer",
    "threat-intel",
    "report-gen",
    "api-gateway",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Ton Nom <ton@email.com>"]
license = "MIT OR Apache-2.0"

[profile.release]
opt-level = 3
strip = true
lto = true
codegen-units = 1
panic = "abort"
